# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../my_project2/From_project1/app3.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 5, 800, 530))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(60, 210, 591, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.takeAttendancebutton = QtWidgets.QPushButton(self.tab)
        self.takeAttendancebutton.setGeometry(QtCore.QRect(280, 330, 161, 25))
        self.takeAttendancebutton.setObjectName("takeAttendancebutton")
        self.trainModelbutton = QtWidgets.QPushButton(self.tab)
        self.trainModelbutton.setGeometry(QtCore.QRect(320, 280, 89, 25))
        self.trainModelbutton.setObjectName("trainModelbutton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(29, 19, 731, 441))
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(49, 49, 631, 341))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.course_code = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.course_code.setMaxLength(6)
        self.course_code.setObjectName("course_code")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.course_code)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.surname = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.surname.setObjectName("surname")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.surname)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.first_name = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.first_name.setObjectName("first_name")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.first_name)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.other_names = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.other_names.setObjectName("other_names")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.other_names)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.mat_no = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mat_no.setObjectName("mat_no")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.mat_no)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.email = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.email.setObjectName("email")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.email)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.program = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.program.setObjectName("program")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.program)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.level = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.level.setMinimum(100)
        self.level.setMaximum(900)
        self.level.setSingleStep(100)
        self.level.setObjectName("level")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.level)
        self.year = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.year.setMinimum(2021)
        self.year.setMaximum(2100)
        self.year.setSingleStep(1)
        self.year.setObjectName("year")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.year)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.capture_button = QtWidgets.QPushButton(self.groupBox_2)
        self.capture_button.setGeometry(QtCore.QRect(280, 400, 171, 25))
        self.capture_button.setObjectName("capture_button")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableView = QtWidgets.QTableView(self.tab_3)
        self.tableView.setGeometry(QtCore.QRect(30, 60, 731, 361))
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.openFile_button = QtWidgets.QPushButton(self.tab_3)
        self.openFile_button.setGeometry(QtCore.QRect(140, 440, 161, 25))
        self.openFile_button.setObjectName("openFile_button")
        self.saveFile_button = QtWidgets.QPushButton(self.tab_3)
        self.saveFile_button.setGeometry(QtCore.QRect(480, 440, 141, 25))
        self.saveFile_button.setObjectName("saveFile_button")
        self.course_detail = QtWidgets.QLineEdit(self.tab_3)
        self.course_detail.setGeometry(QtCore.QRect(232, 20, 131, 25))
        self.course_detail.setObjectName("course_detail")
        self.course_btn = QtWidgets.QPushButton(self.tab_3)
        self.course_btn.setGeometry(QtCore.QRect(390, 20, 141, 25))
        self.course_btn.setObjectName("course_btn")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setEnabled(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionStart_Recognition = QtWidgets.QAction(MainWindow)
        self.actionStart_Recognition.setObjectName("actionStart_Recognition")
        self.menuFile.addAction(self.actionStart_Recognition)
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_10.setText(_translate("MainWindow", "Face Recognition System for Class Attendance Management"))
        self.takeAttendancebutton.setText(_translate("MainWindow", "Take Attendance"))
        self.trainModelbutton.setToolTip(_translate("MainWindow", "Train models each time a new student is enrolled. The trained model is then used in recognizing faces when marking attendance"))
        self.trainModelbutton.setText(_translate("MainWindow", "Train Model"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Welcome Page"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Student\'s Details"))
        self.label.setText(_translate("MainWindow", "Course Title"))
        self.course_code.setPlaceholderText(_translate("MainWindow", "e.g. EEE501"))
        self.label_3.setText(_translate("MainWindow", "Surname"))
        self.surname.setPlaceholderText(_translate("MainWindow", "Doe"))
        self.label_4.setText(_translate("MainWindow", "First Name"))
        self.first_name.setPlaceholderText(_translate("MainWindow", "John"))
        self.label_2.setText(_translate("MainWindow", "Other Names"))
        self.other_names.setPlaceholderText(_translate("MainWindow", "Michael"))
        self.label_5.setText(_translate("MainWindow", "Matriculation Number"))
        self.mat_no.setPlaceholderText(_translate("MainWindow", "UJ/2015/EN/0000"))
        self.label_6.setText(_translate("MainWindow", "Email Address"))
        self.email.setPlaceholderText(_translate("MainWindow", "2015en0012@unijos.edu.ng"))
        self.label_7.setText(_translate("MainWindow", "Program"))
        self.program.setPlaceholderText(_translate("MainWindow", "Electrical and Electronics Engineering"))
        self.label_8.setText(_translate("MainWindow", "Level"))
        self.label_9.setText(_translate("MainWindow", "Year"))
        self.capture_button.setText(_translate("MainWindow", "Capture Biometrics"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Enroll Student"))
        self.openFile_button.setText(_translate("MainWindow", "View Attendance Table"))
        self.saveFile_button.setText(_translate("MainWindow", "Save Modification"))
        self.course_detail.setPlaceholderText(_translate("MainWindow", "Enter Course code"))
        self.course_btn.setText(_translate("MainWindow", "View Course Details"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "View Records"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionStart_Recognition.setText(_translate("MainWindow", "Start Recognition"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
