# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog1.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(400, 389)
        self.buttonBox = QtWidgets.QDialogButtonBox(SettingsDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 340, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(SettingsDialog)
        self.label.setGeometry(QtCore.QRect(70, 10, 261, 31))
        self.label.setStyleSheet("font: 15pt \"Ubuntu\";\n"
"font-style: bold;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(SettingsDialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 60, 361, 269))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.prototxt_file = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.prototxt_file.setObjectName("prototxt_file")
        self.horizontalLayout_2.addWidget(self.prototxt_file)
        self.pushButton_ptf = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_ptf.setObjectName("pushButton_ptf")
        self.horizontalLayout_2.addWidget(self.pushButton_ptf)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.model_file = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.model_file.setObjectName("model_file")
        self.horizontalLayout.addWidget(self.model_file)
        self.pushButton_mf = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_mf.setObjectName("pushButton_mf")
        self.horizontalLayout.addWidget(self.pushButton_mf)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.output_folder = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.output_folder.setObjectName("output_folder")
        self.horizontalLayout_3.addWidget(self.output_folder)
        self.pushButton_opf = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_opf.setObjectName("pushButton_opf")
        self.horizontalLayout_3.addWidget(self.pushButton_opf)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.confidence_2 = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.confidence_2.setMaximum(1.0)
        self.confidence_2.setSingleStep(0.01)
        self.confidence_2.setProperty("value", 0.8)
        self.confidence_2.setObjectName("confidence_2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.confidence_2)
        self.show_warnings_cb = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.show_warnings_cb.setText("")
        self.show_warnings_cb.setChecked(False)
        self.show_warnings_cb.setObjectName("show_warnings_cb")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.show_warnings_cb)
        self.confidence_1 = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.confidence_1.setMaximum(1.0)
        self.confidence_1.setSingleStep(0.01)
        self.confidence_1.setProperty("value", 0.8)
        self.confidence_1.setObjectName("confidence_1")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.confidence_1)
        self.pushButton_reset = QtWidgets.QPushButton(SettingsDialog)
        self.pushButton_reset.setGeometry(QtCore.QRect(20, 340, 89, 25))
        self.pushButton_reset.setObjectName("pushButton_reset")

        self.retranslateUi(SettingsDialog)
        self.buttonBox.accepted.connect(SettingsDialog.accept)
        self.buttonBox.rejected.connect(SettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Settings"))
        self.label.setText(_translate("SettingsDialog", "<h3>Application Settings</h3>"))
        self.label_2.setText(_translate("SettingsDialog", "Show Warnings "))
        self.label_3.setText(_translate("SettingsDialog", "Prototxt File Path"))
        self.prototxt_file.setText(_translate("SettingsDialog", "constants/deploy.prototxt.txt"))
        self.pushButton_ptf.setText(_translate("SettingsDialog", "Browse"))
        self.label_4.setText(_translate("SettingsDialog", "Model File Path"))
        self.model_file.setText(_translate("SettingsDialog", "constants/res10_300x300_ssd_iter_140000.caffemodel"))
        self.pushButton_mf.setText(_translate("SettingsDialog", "Browse"))
        self.label_5.setText(_translate("SettingsDialog", "Output Folder"))
        self.output_folder.setText(_translate("SettingsDialog", "changes/dataset"))
        self.pushButton_opf.setText(_translate("SettingsDialog", "Browse"))
        self.label_7.setText(_translate("SettingsDialog", "Confidence 1"))
        self.label_8.setText(_translate("SettingsDialog", "Confidence 2"))
        self.pushButton_reset.setText(_translate("SettingsDialog", "Reset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SettingsDialog = QtWidgets.QDialog()
    ui = Ui_SettingsDialog()
    ui.setupUi(SettingsDialog)
    SettingsDialog.show()
    sys.exit(app.exec_())
